# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-04-16 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=30)),
                ('postname', models.CharField(max_length=20)),
                ('postaddress', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=10)),
                ('postphone', models.CharField(max_length=11)),
            ],
        ),
    ]
